# Example how to execute Robot Framework Test or Tasks in GitLab CI/CD
# ++++++++++++++++++++++
# Run test job inside robotframework-browser environment and archive reports and results
# This yml-file is inspired by https://github.com/MarketSquare/robotframework-browser/tree/main/docker
#docker run --rm -v $(pwd)/atest/test/:/test --ipc=host --user pwuser --security-opt seccomp=seccomp_profile.json marketsquare/robotframework-browser:latest bash -c "robot --outputdir /test/output /test"
# docker run --rm -v : This command will share the current directory (the directory of your repository) as a shared volume with the docker container, and will make it available inside the container at the path /test


name: Robot Framework

on:
  push:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run: mkdir reports
        - name: Execute tests
          run: |
            docker run \
             --rm \
             -v ${PWD}/reports:/reports \
             -v ${PWD}/tests/:/tests \
             --user pwuser \
             marketsquare/robotframework-browser:latest bash -c "robot /tests"
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
