# Example how to execute Robot Framework Test or Tasks in GitLab CI/CD
# ++++++++++++++++++++++
# Run test job inside robotframework-browser environment and archive reports and results
# This yml-file is inspired by https://github.com/MarketSquare/robotframework-browser/tree/main/docker
#docker run --rm -v $(pwd)/atest/test/:/test --ipc=host --user pwuser --security-opt seccomp=seccomp_profile.json marketsquare/robotframework-browser:latest bash -c "robot --outputdir /test/output /test"

name: Robot Framework

on:
  push:
    branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          run: |
            docker run marketsquare/robotframework-browser:latest bash -c "robot --outputdir ${{ github.workspace }}/reports ${{ github.workspace }}/tests"
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
