# Example how to execute Robot Framework Test or Tasks in GitLab CI/CD with browser library
# ++++++++++++++++++++++
# Run test job inside robotframework-browser environment and archive reports and results
# This yml-file is inspired by https://github.com/MarketSquare/robotframework-browser/tree/main/docker and https://faun.pub/robot-framework-testing-using-github-actions-e0aa8df16fd8


name: Robot Framework

on:
  push:
    branches: [ master ]

jobs:
    Run-robot-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run: |
            mkdir reports 
            chmod a+w reports
        - name: Execute tests
          run: |
            docker run \
             --rm \
             -v ${PWD}/reports:/reports \
             -v ${PWD}/tests/:/tests \
             --user pwuser:pwuser \
             marketsquare/robotframework-browser:latest \
             bash -c "robot --xunit xunit.xml --outputdir /reports /tests"
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports 
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v1
          if: always()
          with:
            files: reports/xunit.xml
            check_name: Robot Framework test results
            comment_title: Robot Framework pass/fail metrics, please see full report from Artifacts
            comment_mode: create new
            hide_comments: off
            pull_request_build: commit
            compare_to_earlier_commit: true