# Example how to execute Robot Framework Test or Tasks in GitLab CI/CD
# ++++++++++++++++++++++
# Run test job inside robotframework-browser environment and archive reports and results
# This yml-file is inspired by https://github.com/robotframework/ci-cd-examples/blob/main/.gitlab-ci.yml

Run hello world test:
  image: marketsquare/robotframework-browser
  stage: test
  script:
    - robot -x xunit.xml -d logs -b console.log tests/hello_world.robot
  artifacts:
    when: always
    expire_in: 1 week
    # archive report.html and log.html from logs folder
    paths:
      - logs
    # attach xunit report to merge requests
    reports:
      junit: logs/xunit.xml